{% set name = "unittest-xml-reporting" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/unittest-xml-reporting/unittest_xml_reporting-4.0.0.tar.gz
  sha256: bfa1ed65e9e6f33c161d04470d89050458cfb65a5a5d0358834ef7ce037d9136

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - setuptools-scm >=6.2.3
  run:
    - python
    - lxml

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - xmlrunner
    - xmlrunner.extra

about:
  home: https://github.com/xmlrunner/unittest-xml-reporting/tree/master/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: unittest-based test runner with Ant/JUnit like XML reporting.
  description:
    - A unittest test runner that can save test results to XML files in xUnit format.
    - The files can be consumed by a wide range of tools, such as build systems,
    - IDEs and continuous integration servers.
  doc_url: https://pypi.org/project/unittest-xml-reporting/
  dev_url: https://github.com/xmlrunner/unittest-xml-reporting

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
