{% set name = "unittest-xml-reporting" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edd8d3170b40c3a81b8cf910f46c6a304ae2847ec01036d02e9c0f9b85762d28

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - lxml

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - xmlrunner
    - xmlrunner.extra

about:
  home: https://github.com/xmlrunner/unittest-xml-reporting/tree/master/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: unittest-based test runner with Ant/JUnit like XML reporting.
  description:
    A unittest test runner that can save test results to XML files in xUnit format. 
    The files can be consumed by a wide range of tools, such as build systems, 
    IDEs and continuous integration servers.
  doc_url: https://pypi.org/project/unittest-xml-reporting/
  dev_url: https://github.com/xmlrunner/unittest-xml-reporting

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
